# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_try.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(400, 600)
        self.centralwidget = QtWidgets.QWidget(Settings)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Settings_Scroll_Area = QtWidgets.QScrollArea(self.centralwidget)
        self.Settings_Scroll_Area.setWidgetResizable(True)
        self.Settings_Scroll_Area.setObjectName("Settings_Scroll_Area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 386, 586))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.hotkey_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.hotkey_label.setGeometry(QtCore.QRect(30, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.hotkey_label.setFont(font)
        self.hotkey_label.setObjectName("hotkey_label")
        self.hotkey_input = QtWidgets.QKeySequenceEdit(self.scrollAreaWidgetContents)
        self.hotkey_input.setGeometry(QtCore.QRect(30, 90, 141, 31))
        self.hotkey_input.setObjectName("hotkey_input")
        self.Settings_Scroll_Area.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.Settings_Scroll_Area)
        Settings.setCentralWidget(self.centralwidget)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "MainWindow"))
        self.hotkey_label.setText(_translate("Settings", "Hotkey"))
